# Generated by Django 5.0.2 on 2024-03-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
    ]
